#%RAML 1.0
title: Firstraml
/Product :
  get:
    description: Fetching the data
    responses:
      200:
        body:
          application/json:
            example:
              {
                "Result" : "successfully fetch the data"
              }

